Side navigation
HHS/nih-oite-website pull request #7
Opened 2022-05-11 23:22 UTC by matthinz

Adds section-based navigation to the side of pages:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/364697/167962905-46c0ca69-fcea-4883-98bd-93fd4f3dd1e4.png">

## Things left to do
- [ ] Tests around logic for building sidenav for a specific page
- [ ] UI for editing page order in CMS
- [ ] Ability to separate navigation title from page title

2022-05-16 21:01 UTC, rahearn requested changes
No major issues, but I think the code can be clarified and simplified in a couple of small cases.

Maybe a conversation for a new story, but I feel like I often see the sidenav used for anchor tags internal to the current page. Is that supported here out of the box? (I think I can see a way to extend this for that use case if not)

2022-05-17 17:42 UTC, matthinz commented on app/models/menu.rb
> +      Page.normalize_path(filename.to_s) == page_path
Yeah I like this suggestion

2022-05-17 17:47 UTC, matthinz commented on spec/models/menu_item_spec.rb
> +    }
Ah! much nicer.

2022-05-17 17:52 UTC, matthinz commented
No support for anchoring down to specific locations on a page, but this could be extended if needed (I think we have an additional level of hierarchy we can use in the USWDS sidenav if we need to)

2022-05-17 19:04 UTC, rahearn requested changes
One issue, that I may have just missed on the last review.

2022-05-17 19:59 UTC, matthinz commented on app/controllers/pages_controller.rb
> -    raise ActionController::RoutingError.new("Not Found")
Whoops! Good catch, I deleted those when I was doing some testing and accidentally committed.

2022-05-17 20:32 UTC, rahearn approved these changes
🎉 

We'll review this at Wednesday's tech meeting.

2022-05-17 20:32 UTC, rahearn commented on spec/requests/pages_spec.rb
> +    it "raises a routing error" do
[praise] 🎉

2022-05-18 13:37 UTC, alvessatnih commented
Looks good to me, too.  Thank you for looping us in, so we can see how this will work moving forward.

2022-05-18 17:22 UTC, rahearn commented
- [ ] The business and/or user value of a story has been met
- [ ] CI pipeline green
- [ ] Code is meaningfully tested
- [ ] UI meets WCAG 2.1 - Levels A and AA
- [ ] Code has deployed to a staging environment
- [ ] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [ ] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [ ] Logical Data Model Diagram is updated on DB schema changes.
- [ ] Public API methods are documented when added or changed.
- [ ] OSCAL templates are completed when security controls are implemented or modified.

2022-05-18 17:41 UTC, ericaWilli approved these changes

2022-05-18 19:30 UTC, merged